language: java
jdk: openjdk8

jobs:
  include:
    - stage: 'setup'
      script: chmod +x mvnw

    - stage: 'check style'
      script: ./mvnw checkstyle:check

    - stage: 'test'
      script: ./mvnw test

    - stage: 'package'
      script: ./mvnw package
      
    - stage: 'deploy'
      before_deploy: skip
      deploy: skip
      after_deploy: skip

notification:
  email: dmitrypetrov93@gmail.com


