language: java
jdk: openjdk8

notification:
  email: dmitrypetrov93@gmail.com

jobs:
  include:
    - stage: 'check style'
      script:
        - chmod +x mvnw
        - ./mvnw checkstyle:check

    - stage: 'test'
      script:
        - chmod +x mvnw
        - ./mvnw test

    - stage: 'package'
      script:
        - chmod +x mvnw
        - ./mvnw package

    - stage: 'deploy'
      script: echo "deploy"