language: java
jdk: openjdk8

notification:
  email: dmitrypetrov93@gmail.com

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: 'check style'
      before_install: chmod +x mvnw
      script: ./mvnw checkstyle:check

    - stage: 'test'
      before_install: chmod +x mvnw
      script: ./mvnw test

    - stage: 'package'
      before_install: chmod +x mvnw
      script: ./mvnw package

    - stage: 'deploy prod'
      if: branch = master
      before_install: chmod +x mvnw
      script: echo "deploy prod"

    - stage: 'deploy dev'
      if: branch = dev
      before_install: chmod +x mvnw
      script: echo "deploy dev"