language: java
jdk: openjdk8

notification:
  email: dmitrypetrov93@gmail.com

jobs:
  include:
    - stage: 'check style'
      before_install: chmod +x mvnw
      script: ./mvnw checkstyle:check

    - stage: 'test'
      before_install: chmod +x mvnw
      script: ./mvnw test

    - stage: 'package'
      before_install: chmod +x mvnw
      script: ./mvnw package

    - stage: 'deploy'
      before_install: chmod +x mvnw
      script: echo "deploy"