language: java
jdk: openjdk8

notification:
  email: dmitrypetrov93@gmail.com

jobs:
  include:
    - stage: 'setup'
      script: chmod +x mvnw

    - stage: 'check style'
      script: ./mvnw checkstyle:check

    - stage: 'test'
      script: ./mvnw test

    - stage: 'package'
      script: ./mvnw package

    - stage: 'deploy'
      script: echo "deploy"